# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SoccerScore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SoccerScore

    pod 'Masonry'
    pod 'AFNetworking'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'MBProgressHUD'

# 滑动锁屏文字样式
    pod 'Shimmer'

# 一些扁平化UI控件
    pod 'FlatUIKit'

# 图片/视频 浏览器
    pod 'MWPhotoBrowser', '~> 2.1.0'

# 中国特色Tabbar（支持特殊+号按钮）
    pod 'CYLTabBarController', '~> 1.6.0'


  target 'SoccerScoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoccerScoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
